steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy
  entrypoint: bash
  args: [ '-c', 'if [ "$BRANCH_NAME" == "develop" ]; then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/dags; else echo "Working on $BRANCH_NAME"; fi']
substitutions:
    _COMPOSER_BUCKET: us-central1-bcs-global-comm-fb7c3617-bucket
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy
  entrypoint: bash
  args: [ '-c', 'if [ "$BRANCH_NAME" == "develop" ]; then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./src gs://${_COMPOSER_BUCKET}; else echo "Working on $BRANCH_NAME"; fi']
substitutions:
    _COMPOSER_BUCKET: demo_inputfiles
options:
  logging: CLOUD_LOGGING_ONLY